Repository StanfordBDHG/ENGAGE-HF-Android, pull requests merged in 2025-06, with the labels that each got.

#8 Update Deployment Setup
  .github/workflows/deployment.yml
  Gemfile
  fastlane/Fastfile
Labels: enhancement

#9 Fix measurement date mapping for invalid unknown values
  app/src/main/kotlin/edu/stanford/bdh/engagehf/bluetooth/measurements/MeasurementToObservationMapper.kt
  app/src/test/kotlin/edu/stanford/bdh/engagehf/bluetooth/measurements/MeasurementToObservationMapperTest.kt
  engagehf-modules/utils/src/main/kotlin/edu/stanford/bdh/engagehf/modules/utils/TimeProvider.kt
  engagehf-modules/utils/src/test/kotlin/edu/stanford/bdh/engagehf/modules/utils/TimeProviderTest.kt
Labels: bug, enhancement

#10 Update GitHub Action Permissions
  .github/workflows/build-test-analyze.yml
  .github/workflows/deployment.yml
  .github/workflows/release.yml
Labels: bug
